name: PackManager
version: 1.0
main: me.junioraww.packmanager.Main
api-version: 1.21
folia-supported: true

commands:
  pack:
    description: Main command to manage resource packs
    usage: /pack [args]
permissions:
  packs.admin:
    default: op